# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'acr'
    repository: 'angularders'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
